---
- name: Gather information from swtiches
  hosts: sw-usa
  gather_facts: no

  tasks:
    - name: "Gather only the interfaces resource facts and no legacy facts"
      cisco.nxos.nxos_facts:
        gather_subset: interfaces

    - name: "Save facts to ./facts folder"
      copy:
        content: "{{ vars }}"
        dest: "./facts/{{ ansible_facts.net_hostname }}_facts.json"
      delegate_to: localhost